apiVersion: v1
kind: ConfigMap
metadata:
  name: samala-config
data:
  DB_HOST: "samala-database.samala-db.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "samala_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: samala-secrets
type: Opaque
stringData:
  DB_USER: "samala_user"
  DB_PASSWORD: "samala_pass"
  JWT_SECRET: "change-me-in-production"
