apiVersion: apps/v1
kind: Deployment
metadata:
  name: samala-backend
  labels:
    app: samala-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samala-backend
  template:
    metadata:
      labels:
        app: samala-backend
    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: backend
          image: 449902674551.dkr.ecr.ap-south-1.amazonaws.com/samala-backend:latest   # <-- replace with your registry image after build+push
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: samala-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: samala-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: samala-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: samala-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: samala-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: samala-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 20
