apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default

  source:
    # Replace with your actual GitHub repo URL after pushing
    repoURL: https://github.com/RakeshSamala09/zero-trust-platform.git
    targetRevision: main
    path: sample-app/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true      # remove resources deleted from Git
      selfHeal: true    # auto-fix manual kubectl changes back to match Git
    syncOptions:
      - CreateNamespace=true
