output "master_public_ip" {
  description = "SSH into this and run kubeadm init — now a fixed Elastic IP, won't change on stop/start"
  value       = aws_eip.master.public_ip
} 

output "worker_public_ips" {
  description = "SSH into these and run kubeadm join (command generated by kubeadm init)"
  value       = aws_instance.k8s_worker[*].public_ip
}

output "ssh_master" {
  value = "ssh -i <your-key>.pem ubuntu@${aws_instance.k8s_master.public_ip}"
}

output "ssh_workers" {
  value = [for ip in aws_instance.k8s_worker[*].public_ip : "ssh -i <your-key>.pem ubuntu@${ip}"]
}

output "oidc_provider_arn" {
  description = "ARN of the self-hosted OIDC provider — needed when configuring kube-apiserver --service-account-issuer"
  value       = aws_iam_openid_connect_provider.self_hosted.arn
}

output "oidc_issuer_url" {
  description = "Use this exact URL as --service-account-issuer on kube-apiserver"
  value        = aws_iam_openid_connect_provider.self_hosted.url
}

output "oidc_s3_bucket" {
  description = "Bucket where you'll upload the OIDC discovery doc + JWKS during kubeadm bootstrap"
  value       = aws_s3_bucket.oidc_provider.bucket
}

output "jenkins_pod_role_arn" {
  description = "IAM role Jenkins pods assume via pod identity — reference this in the K8s service account annotation"
  value       = aws_iam_role.jenkins_pod_role.arn
}

output "estimated_hourly_cost" {
  value = "3x t3.medium = ~$0.125/hr total (~$3/day if left running). STOP or DESTROY instances when not actively working."
}
